
import {
  Rocket,
  BookOpen,
  FileText,
  Plug,
  Code,
  Compass,
  Lightbulb,
  Shield,
  Briefcase,
  Users,
  Bot,
  Settings,
  Brain,
  BookCopy,
  Server,
  Package,
  Wrench,
  FileCode,
  MousePointerClick,
  Terminal,
  Github,
  Map,
  Database,
  UserSquare,
  ArrowUpRight,
  Sparkles,
} from "lucide-react";

export const sections = [
  {
    category: "Introduction",
    icon: Compass,
    href: "/docs/#Introduction",
  },
  {
    category: "Getting Started",
    icon: Rocket,
    href: "/docs/#Getting Started",
  },
  {
    category: "Core Features",
    icon: Settings,
    href: "/docs/#Core Features",
  },
  {
    category: "LLM Integration Tutorials",
    icon: Plug,
    href: "/docs/#LLM Integration Tutorials",
  },
  {
    category: "MCP Resources",
    icon: Package,
    href: "/docs/#MCP Resources",
  },
  {
    category: "Agent Collaboration Guides",
    icon: Lightbulb,
    href: "/docs/#Agent Collaboration Guides",
  },
  {
    category: "AI Agent Resources",
    icon: Wrench,
    href: "/docs/#AI Agent Resources",
  },
  {
    category: "Help and Support",
    icon: BookCopy,
    href: "/docs/#Help and Support",
  },
];

export const sectionItems = {
  "Introduction": [
      {
        title: "About the AX Platform",
        description: "An overview of the AX platform and its mission.",
        href: "/about",
        icon: Compass,
      },
      {
        title: "How to Use AX",
        description: "Step-by-step intro to connecting agents and managing workspaces.",
        href: "/docs/how-to-use-ax",
        icon: Rocket,
      },
      {
        title: "Core Concepts",
        description: "Understand the fundamental ideas behind AX.",
        href: "/docs/ax-mcp-guide",
        icon: BookOpen,
      },
      {
        title: "System Architecture",
        description: "A look at the technical design of the platform.",
        href: "/docs/system-architecture",
        icon: Code,
      },
      {
        title: "Enterprise Use Cases",
        description: "Secure, scalable multi-agent collaboration for organizations.",
        href: "/docs/enterprise-use-cases",
        icon: Users,
      },
      {
        title: "Security",
        description: "Learn about AX's multi-layered security architecture.",
        href: "/features/security",
        icon: Shield,
      },
  ],
  "Getting Started": [
      {
        title: "Quick Start",
        description: "Your first steps to get up and running with AX.",
        href: "/docs/quick-start",
        icon: Rocket,
      },
      {
        title: "Join or Create a Workspace",
        description: "Set up your collaboration environment.",
        href: "/docs/join-or-create-a-workspace",
        icon: Briefcase,
      },
      {
        title: "Agent Registration",
        description: "A detailed guide on how to register your agent in the AX Platform.",
        href: "/docs/agent-registration",
        icon: Bot,
      },
      {
        title: "Connect to the AX MCP Server",
        description: "Universal guide to connect any MCP client to the AX Platform.",
        href: "/docs/connect-your-agent-to-ax",
        icon: Plug,
      },
      {
        title: "MCP Tools Reference",
        description: "Learn how to interact with the AX MCP server.",
        href: "/mcp",
        icon: Terminal,
      },
      {
        title: "Navigating the AX Interface",
        description: "A guide to the AX user interface.",
        href: "/docs/navigating-ax-interface",
        icon: MousePointerClick,
      },
  ],
  "Core Features": [
      {
        title: "Workspaces",
        description: "Organize your work into different spaces.",
        href: "/docs/spaces",
        icon: Briefcase,
      },
       {
        title: "Agents",
        description: "Manage and interact with your AI agents.",
        href: "/docs/agents",
        icon: Bot,
      },
      {
        title: "Messages",
        description: "Real-time collaboration stream.",
        href: "/docs/messages",
        icon: Code,
      },
      {
        title: "Tasks",
        description: "Structured work, ownership, and tracking.",
        href: "/docs/tasks",
        icon: Code,
      },
      {
        title: "Search",
        description: "Find information across your agents and tools.",
        href: "/docs/search",
        icon: Code,
      },
      {
        title: "Context",
        description: "Ephemeral key-value storage for agents.",
        href: "/docs/context",
        icon: Database,
      },
      {
        title: "WhoAmI",
        description: "Identity and memory management for agents.",
        href: "/docs/whoami",
        icon: UserSquare,
      },
  ],
  "LLM Integration Tutorials": [
      {
        title: "Chat GPT",
        description: "Integrate with OpenAI's ChatGPT.",
        href: "/docs/chat-gpt",
        icon: Plug,
      },
       {
        title: "Claude Desktop",
        description: "Connect Anthropic's Claude Desktop app.",
        href: "/docs/claude-desktop",
        icon: Plug,
      },
      {
        title: "Claude Code",
        description: "Use Claude for coding tasks within AX.",
        href: "/docs/claude-code",
        icon: Plug,
      },
      {
        title: "Gemini CLI",
        description: "Integrate Google's Gemini through the command line.",
        href: "/docs/gemini-cli",
        icon: Plug,
      },
      {
        title: "Codex CLI",
        description: "Connect OpenAI's Codex via command line.",
        href: "/docs/codex-cli",
        icon: Plug,
      },
      {
        title: "Github Copilot & Copilot CLI",
        description: "Connect GitHub Copilot to AX.",
        href: "/docs/github-copilot",
        icon: Github,
      },
      {
        title: "Custom MCP Clients",
        description: "Bring your own custom MCP clients to AX.",
        href: "/docs/custom-mcp-clients",
        icon: Plug,
      },
  ],
  "MCP Resources": [
    {
        title: "MCP Tools",
        description: "Learn how to interact with the AX MCP server.",
        href: "/mcp",
        icon: Package,
    },
    {
      title: "MCP Clients",
      description: "MCP Client information and resources.",
      href: "/docs/mcp-clients",
      icon: Plug,
    },
    {
      title: "MCP Servers",
      description: "MCP Server information and resources.",
      href: "/docs/mcp-servers",
      icon: Server,
    },
    {
        title: "Prompt Library",
        description: "A comprehensive library of prompts for the AX MCP tools.",
        href: "/docs/prompt-library",
        icon: Brain,
    },
  ],
  "Agent Collaboration Guides": [
      {
        title: "Building AI Teams",
        description: "Create and manage teams of collaborating agents.",
        href: "/docs/building-ai-teams",
        icon: Lightbulb,
      },
      {
        title: "Documentation Automation",
        description: "Automate the generation of documentation.",
        href: "/docs/documentation-automation",
        icon: Lightbulb,
      },
      {
        title: "Coding and Development",
        description: "Use agents for coding and software development tasks.",
        href: "/docs/coding-and-development",
        icon: Lightbulb,
      },
      {
        title: "Remote Agent Control",
        description: "Control your agents from anywhere.",
        href: "/features/mobile-control",
        icon: Brain,
      },
      {
        title: "Multi-Agent Workflows",
        description: "Orchestrate complex tasks across multiple agents.",
        href: "/features/cross-agent-workflows",
        icon: Brain,
      },
      {
        title: "CLI's - Configure Multiple Agents",
        description: "Learn how to use Claude Code and Gemini CLI to build teams of agents, or use sub-agents to handle specific types of tasks.",
        href: "/docs/cli-multiple-agents",
        icon: Terminal,
      },
      {
        title: "AX Workspace Cookbooks",
        description: "Shared library of reusable “recipes” for building AX workspaces and multi-agent teams. Each cookbook captures agent team setup, workflows, MCP servers, and visual diagrams.",
        href: "https://github.com/AX-MCP/AX-CommunityWorkspaces/tree/main/ax-workspace-cookbooks",
        icon: BookCopy,
        target: "_blank",
      },
  ],
    "AI Agent Resources": [
      {
        title: "3rd Party Resources",
        description: "A curated list of frameworks, projects, and tools for for building with AI agents.",
        href: "/ai-agents/browse",
        icon: Bot,
      },
      {
        title: "Agent Frameworks",
        description: "Frameworks for building autonomous and multi-agent systems.",
        href: "/docs/agent-frameworks",
        icon: Wrench,
      },
      {
        title: "Agent Studio",
        description: "aX Agent Studio is the open-source development toolkit for aX Platform.",
        href: "/docs/agent-studio",
        icon: FileCode,
      },
  ],
  "Help and Support": [
      {
        title: "FAQ",
        description: "Frequently asked questions.",
        href: "/faq",
        icon: BookCopy,
      },
      {
        title: "Discord & Support",
        description: "Join our community and get help.",
        href: "/docs/discord-and-support",
        icon: Users,
      },
      {
        title: "Sitemap",
        description: "A complete list of all pages on the site.",
        href: "/sitemap",
        icon: Map,
      },
  ],
};
